apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polarstomps
spec:
  project: default
  source:
    repoURL: https://github.com/howdoicomputer/polarstomps-argo
    targetRevision: main
    path: polarstomps-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: polarstomps
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        elbv2.k8s.aws/pod-readiness-gate-inject: enabled
    syncOptions:
      - CreateNamespace=true
