apiVersion: apps/v1
kind: Deployment
metadata:
  name: polarstomps
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: polarstomps
  template:
    metadata:
      labels:
        app: polarstomps
    spec:
      serviceAccountName: polarstomps
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "eks-aws-secrets"
      containers:
        - image: howdoicomputer/polarstomps:v4
          name: polarstomps
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "0.5"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: DATABASE_URL
              value: "sqlite:///./sqlite.db"
