apiVersion: apps/v1
kind: Deployment
metadata:
  name: polarstomps
spec:
  replicas: 10
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: polarstomps
  template:
    metadata:
      labels:
        app: polarstomps
    spec:
      containers:
        - image: howdoicomputer/polarstomps:v4
          name: polarstomps
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "0.5"
