apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "0 0 23 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: polarstompos
              image: polarstomps:v3
              imagePullPolicy: IfNotPresent
              command:
                - manage.py
                - start-todays-trips
          restartPolicy: OnFailure
