apiVersion: v1
kind: Service
metadata:
  name: polarstomps
  namespace: polarstomps
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      name: http
  selector:
    app: polarstomps
