apiVersion: v1
kind: Service
metadata:
  name: polarstomps
  namespace: polarstomps
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: polarstomps
