apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: eks-aws-secrets
  namespace: polarstomps
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "eksSecret"
        objectType: "secretsmanager"
