apiVersion: apps/v1
kind: Deployment
metadata:
  name: polarstomps
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: polarstomps
  template:
    metadata:
      labels:
        app: polarstomps
    spec:
      serviceAccountName: polarstomps
      volumes:
      containers:
        - image: howdoicomputer/polarstomps:v4
          name: polarstomps
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "0.5"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db
                  key: db
